name: Api Build & Test & Deploy

on:
  push:
    branches: [ master ]
    paths: [ 'api/**/*' ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
  WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}

jobs:
  build-api:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: go build main.go

  deploy-api:
    needs: [build-api]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12

        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: "ytmparty-api"
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "api"
          
  announce-api:
    needs: [deploy-api]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/discord-action@master

        with:
          webhook_id: ${{ env.WEBHOOK_ID }}
          webhook_token: ${{ env.WEBHOOK_TOKEN }}
          args: "the project was deployed without any problems"
